[devshell]
packages = [
    "go",
    "gotests",
    "gopls",
    "rustc",
    "rustfmt",
    "cargo",
    "grpcurl",
    "protobuf",
    "protoc-gen-go",
    "protoc-gen-go-grpc",
    "pkgs.stdenv.cc"
]
